### ISSUE TITLE
Display colored underline/undercurl in tmux in wsl in Windows Terminal

### ISSUE THREAD

**Issue by leonasdev** [leonasdev/.dotfiles#15]
Windows Terminal Preview 1.20 now support colored curly, dashed, or dotted and doubled underlines. ref: [Windows Terminal Preview 1.20 Release](https://devblogs.microsoft.com/commandline/windows-terminal-preview-1-20-release/)

If using neovim without `tmux`, we can workaround by: https://github.com/neovim/neovim/issues/26744#issuecomment-1918867789

But if using `tmux`, Windows Terminal cannot display colored underline/undercurl properly. (though non-colored is worked)

Following config of tmux still cannot solve it:
```bash
# Undercurl
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0
```  

You can test by execute this command in shell:
```bash
printf "\x1b[58:2::255:0:0m\x1b[4:1msingle\x1b[4:2mdouble\x1b[4:3mcurly\x1b[4:4mdotted\x1b[4:5mdashed\x1b[0m\n"
```

without `tmux`:
![image](https://github.com/leonasdev/.dotfiles/assets/39915562/6316a5de-620c-4827-8257-8c84816f108e)

with `tmux` and the config above:
![image](https://github.com/leonasdev/.dotfiles/assets/39915562/5332b4f4-d0be-4ae3-92f7-f9e35f376f4d)

**Comment by leonasdev** [comment]
Turn out you need a different `Setulc` with Windows Terminal, perhaps `wezterm`:
(notice that this one have two additional `:` )
```bash
set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m' # underscore colours - needs tmux-3.0 (wsl2 in Windows Terminal)
```

So we can combine with this config to acheive OS specific `Setulc` for tmux:
```bash
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Check if we are in WSL
if-shell 'test -n "$WSL_DISTRO_NAME"' {
  set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m' # underscore colours - needs tmux-3.0 (wsl2 in Windows Terminal)
}
```

Now we can show colored underline/undercurl in both `tmux` and `neovim` 😊:
![image](https://github.com/leonasdev/.dotfiles/assets/39915562/733921c2-847e-4f87-ab20-9506c9f280b5)
![image](https://github.com/leonasdev/.dotfiles/assets/39915562/e089c87e-4d29-41f8-b3b0-a36e1b0f6782)

References:
- https://github.com/tmux/tmux/issues/3769
- https://github.com/orgs/tmux/discussions/3827#discussioncomment-8330054
- https://github.com/microsoft/terminal/discussions/16636
- https://github.com/microsoft/terminal/issues/16637

**Comment by dead8309** [comment]
Hey, was struggling to make undercurls work for days. Thanks 🤗

**Comment by sayandipdutta** [comment]
@leonasdev I was following your trick, and it was working fine for almost 3 months now. But recently it stopped working for some reason. Changing this line:
`set -ag terminal-overrides ",xterm-256color:RGB"`
to this:
`set -as terminal-overrides ",*256col*:Tc"`

solved it for me. Thanks

**Comment by james1236** [comment]
Thanks! This solves colored curly underlines, but I still cannot get dotted underlines when nesting tmux and nvim (nvim alone works fine). Spent a while failing to fix this, so I'm putting the details here for anyone else to compare with

Windows terminal capabilities for reference (no tmux, no nvim):
<img width="1124" height="633" alt="Image" src="https://github.com/user-attachments/assets/fee01c3a-0f05-4669-a530-3b384f81c80c" />

Nvim (no tmux):

<img width="463" height="192" alt="Image" src="https://github.com/user-attachments/assets/f71ab003-c8af-457c-985a-9ca4175412c5" />

Nvim inside tmux:

<img width="457" height="181" alt="Image" src="https://github.com/user-attachments/assets/ce593524-91bb-4368-8932-02462f681773" />

<details>

<summary>Tmux config</summary>

```sh
set -g default-terminal "tmux-256color"
# Enable truecolor
set -as terminal-overrides ',xterm*:Tc'
# set -ag terminal-overrides ",xterm-256color:RGB"

# Extended underline styles (single, double, curly, dotted, dashed)
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

if-shell 'test -n "$WSL_DISTRO_NAME"' { # Check if we are in WSL
  set -as terminal-overrides ',*:Setulc=\E[58::2::::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m' # underscore colours - needs tmux-3.0 (wsl2 in Windows Terminal)
}

# Overline
set -as terminal-overrides ',*:Smol=\E[53m'
set -as terminal-overrides ',*:Rmol=\E[55m'

# Hyperlinks (OSC 8) - not doing anything 
set -as terminal-overrides ',*:Ms=\E]8;;%p1%s\E\\'

```

</details>

<details>

<summary>Text format testing script</summary>

```sh
testtextformat() {
  clear
  echo "--- [0] TERM & ENV ---"
  echo "TERM: $TERM"
  echo "COLORTERM: $COLORTERM"
  printf "\n"

  echo "--- [1] STANDARD TEXT ATTRIBUTES ---"
  printf "\e[1mBold\e[0m | \e[2mDim\e[0m | \e[3mItalic\e[0m | \e[4mUnderline\e[0m | \e[5mBlink\e[0m | \e[7mInverse\e[0m | \e[8mHidden(> <)\e[0m | \e[9mStrikethrough\e[0m\n\n"

  echo "--- [2] ADVANCED UNDERLINE STYLES (Smulx) ---"
  printf "\e[4:1mSingle\e[0m | \e[4:2mDouble\e[0m | \e[4:3mCurly\e[0m | \e[4:4mDotted\e[0m | \e[4:5mDashed\e[0m\n\n"

  echo "--- [3] COLORED UNDERLINES (Setulc - RGB) ---"
  printf "\e[4:3m\e[58:2::255:0:0mRed-Curly\e[0m | \e[4:4m\e[58:2::0:255:0mGreen-Dotted\e[0m | \e[4:5m\e[58:2::0:0:255mBlue-Dashed\e[0m\n\n"

  echo "--- [4] OVERLINE (Smol) ---"
  printf "\e[53mThis text has an overline\e[0m\n\n"

  echo "--- [5] TRUE COLOR (24-bit RGB) ---"
  printf "\e[38:2::255:87:51mDeep Orange\e[0m | \e[38:2::51:255:189mAquamarine\e[0m | \e[38:2::189:51:255mPurple\e[0m\n\n"

  echo "--- [6] HYPERLINKS (OSC 8) ---"
  printf "\e]8;;https://github.com\e\\Clickable GitHub Link\e]8;;\e\\ \n\n"

  echo "--- TEST COMPLETE ---"
}

```

</details>
