### ISSUE TITLE
Can't install using fish because can't detect neovim version correctly

### ISSUE THREAD

**Issue by PurofPanacea** [leonasdev/.dotfiles#16]
bash (curl -s https://raw.githubusercontent.com/leonasdev/.dotfiles/master/install.sh | psub)
Welcome to leonasdev's dotfiles installation!

**Installation will override your current [neovim, fish, oh-my-posh] configuration!**
Continue installation?
[y/n]: y
--------------------------------------------------------------------------------
Checking Neovim version...
[ERROR]: Neovim version needs to greater then 0.9.0 !

pacman -Qi neovim                                                            
Name            : neovim
Version         : 0.10.2-2
Description     : Fork of Vim aiming to improve user experience, plugins, and GUIs
Architecture    : x86_64
URL             : https://neovim.io
Licenses        : Apache-2.0  LicenseRef-vim
Groups          : None
Provides        : vim-plugin-runtime
Depends On      : libluv  libutf8proc  libuv  libvterm>=0.3.3  lua51-lpeg  luajit
                  msgpack-c  tree-sitter  tree-sitter-c  tree-sitter-lua
                  tree-sitter-markdown  tree-sitter-query  tree-sitter-vim
                  tree-sitter-vimdoc  unibilium
Optional Deps   : python-pynvim: for Python plugin support (see :help python)
                  xclip: for clipboard support on X11 (or xsel) (see :help clipboard)
                  [installed]
                  xsel: for clipboard support on X11 (or xclip) (see :help clipboard)
                  wl-clipboard: for clipboard support on wayland (see :help clipboard)
                  [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 26.96 MiB
Packager        : Daniel M. Capella <polyzen@archlinux.org>
Build Date      : Thu 10 Oct 2024 04:39:02 AM +08
Install Date    : Tue 22 Oct 2024 03:41:28 PM +08
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

**Comment by danz-km** [comment]
I tried uninstalling and reinstalling neovim, but it can't detect that my neovim version is greater than 0.9.0

bash (curl -s https://raw.githubusercontent.com/leonasdev/.dotfiles/master/install.sh | psub)
Welcome to leonasdev's dotfiles installation!

**Installation will override your current [neovim, fish, oh-my-posh] configuration!**
Continue installation?
[y/n]: y
--------------------------------------------------------------------------------
Checking Neovim version...
[ERROR]: Neovim version needs to greater then 0.9.0 !

╭─    ~ ────────────────────────────────────────────────────────────── 15:46:37 ─╮
╰─❯ pacman -Qi neovim                                                                ─╯
Name            : neovim
Version         : 0.10.2-2
Description     : Fork of Vim aiming to improve user experience, plugins, and GUIs
Architecture    : x86_64
URL             : https://neovim.io
Licenses        : Apache-2.0  LicenseRef-vim
Groups          : None
Provides        : vim-plugin-runtime
Depends On      : libluv  libutf8proc  libuv  libvterm>=0.3.3  lua51-lpeg  luajit
                  msgpack-c  tree-sitter  tree-sitter-c  tree-sitter-lua
                  tree-sitter-markdown  tree-sitter-query  tree-sitter-vim
                  tree-sitter-vimdoc  unibilium
Optional Deps   : python-pynvim: for Python plugin support (see :help python)
                  xclip: for clipboard support on X11 (or xsel) (see :help clipboard)
                  [installed]
                  xsel: for clipboard support on X11 (or xclip) (see :help clipboard)
                  wl-clipboard: for clipboard support on wayland (see :help clipboard)
                  [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 26.96 MiB
Packager        : Daniel M. Capella <polyzen@archlinux.org>
Build Date      : Thu 10 Oct 2024 04:39:02 AM +08
Install Date    : Tue 22 Oct 2024 03:46:30 PM +08
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

**Comment by danz-km** [comment]
All I had to do was just uninstall neovim from my system.

**Comment by danz-km** [comment]
All I had to do was just uninstall neovim from my system.
